# Generated by Django 5.2.15 on 2026-06-22 05:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash_flow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashflow",
            name="created_at",
            field=models.DateField(
                default=django.utils.timezone.now, help_text="Дата создания записи"
            ),
        ),
    ]
