# Generated by Django 5.2.15 on 2026-06-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash_flow", "0002_alter_cashflow_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashflow",
            name="cash",
            field=models.DecimalField(
                decimal_places=2, help_text="Итоговая сумма", max_digits=10
            ),
        ),
    ]
